# Generated by Django 3.0 on 2020-02-04 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0003_contractor'),
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('mobile', models.IntegerField()),
                ('email', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('nationalid', models.IntegerField()),
                ('grade', models.CharField(max_length=10)),
                ('salary', models.IntegerField()),
            ],
        ),
    ]
