# Generated by Django 3.0 on 2020-02-04 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0005_contracts'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='status',
            field=models.CharField(default='available', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='status',
            field=models.CharField(default='available', max_length=20),
        ),
    ]
