# Generated by Django 3.0 on 2020-02-05 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0006_auto_20200204_1752'),
    ]

    operations = [
        migrations.CreateModel(
            name='selectemployee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wid', models.IntegerField()),
                ('eid', models.IntegerField()),
            ],
        ),
    ]
